stages:
  data_ingestion:
    cmd: uv run src/churn_modelling/pipeline/stage_01_data_ingestion.py
    deps:
      - src/churn_modelling/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data/ingestion
  data_validation:
    cmd: uv run src/churn_modelling/pipeline/stage_02_data_validation.py
    deps:
      - src/churn_modelling/pipeline/stage_02_data_validation.py
      - config/config.yaml
      - artifacts/data/ingestion/ingested/train.csv
      - artifacts/data/ingestion/ingested/test.csv
    outs:
      - artifacts/data/validation
  data_transfomation:
    cmd: uv run src/churn_modelling/pipeline/stage_03_data_transformation.py
    deps:
      - src/churn_modelling/pipeline/stage_03_data_transformation.py
      - config/config.yaml
      - artifacts/data/validation/valid/train.csv
      - artifacts/data/validation/valid/test.csv
      - artifacts/data/validation/report.json
    outs:
      - artifacts/data/transformation
  