stages:
  data_ingestion:
    cmd: uv run src/churn_modelling/pipeline/stage_01_data_ingestion.py
    deps:
      - src/churn_modelling/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data/ingestion
  