ROOT_DIR: artifacts
DATA:
  ROOT_DIR: data
  INGESTION:
    ROOT_DIR: ingestion 
    FEATURE_STORE:
      ROOT_DIR: feature_store 
      RAW_DATA: raw.csv 
    INGESTED:
      ROOT_DIR: ingested 
      TRAIN_DATA: train.csv 
      TEST_DATA: test.csv 
  VALIDATION:
    ROOT_DIR: validation 
    VALID:
      ROOT_DIR: valid 
    INVALID: 
      ROOT_DIR: invalid 
    TRAIN_DATA: train.csv 
    TEST_DATA: test.csv 
    REPORT_FILE: report.json
  TRANSFORMATION:
    ROOT_DIR: transformation 
    TRAIN_DATA: train.csv 
    TEST_DATA: test.csv
    FEATURES: feature_names.json
    PREPROCESSOR: preprocessor.pkl 
MODEL:
  ROOT_DIR: model 
  TRAINING: 
    ROOT_DIR: train 
    SCORES_FILE: search_output.json 
    BEST_PARAMS_FILE: best_params.json
    ESTIMATOR_WEIGHT_FILE: estimator_weights.pkl 
    OPTIMIZER_FILE: optimizer.pkl 
    ESTIMATOR_HISTORY_FILE: history.json 
  PREDICTION:
    ROOT_DIR: predictions 
    FILE_EXT: .json
  