columns:
  Age: int64
  Balance: float64
  CreditScore: int64
  CustomerId: int64
  EstimatedSalary: float64
  Exited: int64
  Gender: object
  Geography: object
  HasCrCard: int64
  IsActiveMember: int64
  NumOfProducts: int64
  RowNumber: int64
  Surname: object
  Tenure: int64
numerical_columns:
- RowNumber
- CustomerId
- CreditScore
- Age
- Tenure
- Balance
- NumOfProducts
- HasCrCard
- IsActiveMember
- EstimatedSalary
- Exited
