name: CI/CD

on:
  push:
    branches: [ main ]
    paths-ignore: [ README.md ]

env: 
  MLFLOW_IMAGE: churnmodelling.azurecr.io/mlflow-server:latest
  MLAPP_IMAGE: churnmodelling.azurecr.io/ml-app:latest

jobs:
  build-and-push:
    name: Build & Push Images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: churnmodelling.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker images
        run: docker compose build --no-cache 

      - name: Push images to ACR
        run: docker compose push

  deploy:
    name: Continuous Deployment
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }} 
      
      - name: Stop all running containers and Cleaning previous images, containers and volumes
        run: | 
            docker compose down
            docker system prune -af

      - name: Deploy on Azure VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker compose pull
            docker compose up -d
