name: CI/CD

on:
  push:
    branches: [ main ]
    paths-ignore: [ README.md ]

jobs:
  build-and-push:
    name: Build & Push Images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: churnmodelling.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker images
        run: docker compose build --no-cache 

      - name: Push images to ACR
        run: | 
          docker push churnmodelling.azurecr.io/mlflow-server:latest
          docker push churnmodelling.azurecr.io/ml-app:latest

  deploy:
    name: Continuous Deployment
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }} 

      - name: Upload docker-compose.yml to VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: "/home/azureuser/app"

      - name: Run docker compose on Azure VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/azureuser/app

            echo "Stop all running containers"
            docker compose down

            echo "Clean prevous images, containers, volumes"
            docker system prune -af
            
            echo "Pulling latest images from ACR..."
            docker compose pull
            
            echo "Starting application..."
            docker compose up -d --remove-orphans
            
            echo "Application started."