from dataclasses import dataclass 
from churn_modelling.utils import load_yaml 


CONFIG = load_yaml("config/config.yaml")

@dataclass 
class DataIngestionConstants:
    ROOT_DIR = CONFIG.ROOT_DIR 
    DATA_ROOT_DIR = CONFIG.DATA.ROOT_DIR
    INGESTION_ROOT_DIR = CONFIG.DATA.INGESTION.ROOT_DIR 
    FEATURE_STORE_ROOT_DIR = CONFIG.DATA.INGESTION.FEATURE_STORE.ROOT_DIR
    RAW_DATA_FILE_NAME = CONFIG.DATA.INGESTION.FEATURE_STORE.RAW_DATA
    INGESTED_ROOT_DIR = CONFIG.DATA.INGESTION.INGESTED.ROOT_DIR
    TRAIN_DATA_FILE_NAME = CONFIG.DATA.INGESTION.INGESTED.TRAIN_DATA
    TEST_DATA_FILE_NAME = CONFIG.DATA.INGESTION.INGESTED.TEST_DATA
    DATABASE_FILE_PATH = 'database/Bank.db'
    DATABASE_TABLE_NAME = 'ChurnModelling'

@dataclass 
class DataValidationConstants:
    ROOT_DIR = CONFIG.ROOT_DIR
    DATA_ROOT_DIR = CONFIG.DATA.ROOT_DIR
    VALIDATION_ROOT_DIR = CONFIG.DATA.VALIDATION.ROOT_DIR
    VALID_ROOT_DIR = CONFIG.DATA.VALIDATION.VALID.ROOT_DIR
    INVALID_ROOT_DIR = CONFIG.DATA.VALIDATION.INVALID.ROOT_DIR
    TRAIN_DATA = CONFIG.DATA.VALIDATION.TRAIN_DATA
    TEST_DATA = CONFIG.DATA.VALIDATION.TEST_DATA
    REPORT_FILE = CONFIG.DATA.VALIDATION.REPORT_FILE
    SCHEMA_FILE_PATH = 'schema/schema.yaml'

