from churn_modelling.utils import load_yaml 
from dataclasses import dataclass 
import os 


CONFIG = load_yaml("config/config.yaml")

@dataclass 
class DataIngestionConstants:
    ROOT_DIR = CONFIG.ROOT_DIR 
    DATA_ROOT_DIR = CONFIG.DATA.ROOT_DIR
    INGESTION_ROOT_DIR = CONFIG.DATA.INGESTION.ROOT_DIR 
    FEATURE_STORE_ROOT_DIR = CONFIG.DATA.INGESTION.FEATURE_STORE.ROOT_DIR
    RAW_DATA_FILE_NAME = CONFIG.DATA.INGESTION.FEATURE_STORE.RAW_DATA
    INGESTED_ROOT_DIR = CONFIG.DATA.INGESTION.INGESTED.ROOT_DIR
    TRAIN_DATA_FILE_NAME = CONFIG.DATA.INGESTION.INGESTED.TRAIN_DATA
    TEST_DATA_FILE_NAME = CONFIG.DATA.INGESTION.INGESTED.TEST_DATA
    DATABASE_FILE_PATH = 'database/Bank.db'
    DATABASE_TABLE_NAME = 'ChurnModelling'

@dataclass 
class DataValidationConstants:
    ROOT_DIR = CONFIG.ROOT_DIR
    DATA_ROOT_DIR = CONFIG.DATA.ROOT_DIR
    VALIDATION_ROOT_DIR = CONFIG.DATA.VALIDATION.ROOT_DIR
    VALID_ROOT_DIR = CONFIG.DATA.VALIDATION.VALID.ROOT_DIR
    INVALID_ROOT_DIR = CONFIG.DATA.VALIDATION.INVALID.ROOT_DIR
    TRAIN_DATA = CONFIG.DATA.VALIDATION.TRAIN_DATA
    TEST_DATA = CONFIG.DATA.VALIDATION.TEST_DATA
    REPORT_FILE = CONFIG.DATA.VALIDATION.REPORT_FILE
    SCHEMA_FILE_PATH = 'schema/schema.yaml'

@dataclass 
class DataTransformationConstants:
    ROOT_DIR = CONFIG.ROOT_DIR
    DATA_ROOT_DIR = CONFIG.DATA.ROOT_DIR
    TRANSFORMATION_ROOT_DIR = CONFIG.DATA.TRANSFORMATION.ROOT_DIR
    TRAIN_DATA = CONFIG.DATA.TRANSFORMATION.TRAIN_DATA
    TEST_DATA = CONFIG.DATA.TRANSFORMATION.TEST_DATA
    FEATURES = CONFIG.DATA.TRANSFORMATION.FEATURES
    PREPROCESSOR = CONFIG.DATA.TRANSFORMATION.PREPROCESSOR

@dataclass 
class ModelTrainerConstants:
    ROOT_DIR = CONFIG.ROOT_DIR
    MODEL_ROOT_DIR = CONFIG.MODEL.ROOT_DIR
    TRAINING_ROOT_DIR = CONFIG.MODEL.TRAINING.ROOT_DIR
    SCORES_FILE = CONFIG.MODEL.TRAINING.SCORES_FILE
    BEST_PARAMS_FILE = CONFIG.MODEL.TRAINING.BEST_PARAMS_FILE
    ESTIMATOR_WEIGHT_FILE = CONFIG.MODEL.TRAINING.ESTIMATOR_WEIGHT_FILE
    OPTIMIZER_FILE = CONFIG.MODEL.TRAINING.OPTIMIZER_FILE
    ESTIMATOR_HISTORY_FILE = CONFIG.MODEL.TRAINING.ESTIMATOR_HISTORY_FILE
    PARAMS_FILE_PATH = "params.json"
    TARGET = "Exited"

@dataclass 
class ModelPredictionConstants: 
    ROOT_DIR = CONFIG.MODEL.PREDICTION.ROOT_DIR
    FILE_EXT = CONFIG.MODEL.PREDICTION.FILE_EXT 
    BUCKET = os.getenv("S3_BUCKET")
    OBJECT = os.getenv("S3_BUCKET_PREDICTION_OBJECT")
